# Generated by Django 5.0.4 on 2024-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image_url", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("isUpdate", models.BooleanField())
            ],
        ),
    ]
