# Generated by Django 5.0.4 on 2024-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("slug", models.CharField(max_length=50)),
            ],
        ),
    ]
