# Generated by Django 5.0.4 on 2024-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0003_food_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
