# Generated by Django 5.0.4 on 2024-04-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0004_alter_food_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="foodMain.categories",
            ),
        ),
    ]
