# Generated by Django 5.0.4 on 2024-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0005_food_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
