# Generated by Django 5.0.4 on 2024-04-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0006_alter_categories_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="category",
        ),
        migrations.AddField(
            model_name="food",
            name="categories",
            field=models.ManyToManyField(to="foodMain.categories"),
        ),
    ]
