# Generated by Django 5.0.4 on 2024-04-16 16:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0007_remove_food_category_food_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="subtitle",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="food",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
