# Generated by Django 5.0.4 on 2024-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodMain", "0008_food_subtitle_alter_food_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="image_url",
            field=models.CharField(default="", max_length=50),
        ),
    ]
